# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19bd57655d4bf1678f527728cfd96a7e09dcc76fc00f56d47b3b50082deeb8d5881e228fb32c9b781384e5562ad9316afa5b14d935a39502ab9c86e332328b5e

test:
  secret_key_base: 53fb119b4b1c5ca4b747c93bef7217d03f83bbfb9ecf0b6c74a22c3ab1e49eb24252f84a91c0a838e308bdfb41f09ce95b7fad32eec987fb67ad6d3d70f25735

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
